-- Script de carga de datos de prueba

-- AUTORES
INSERT INTO autores_autor (nombre, apellido) VALUES
('Juan', 'Pérez'),
('María', 'González'),
('Carlos', 'López'),
('Ana', 'Martínez'),
('Luis', 'Hernández'),
('Laura', 'García'),
('Jorge', 'Rodríguez'),
('Sofía', 'Fernández'),
('Diego', 'Sánchez'),
('Valentina', 'Torres'),
('Andrés', 'Ramírez'),
('Camila', 'Díaz'),
('Fernando', 'Morales'),
('Isabella', 'Vásquez'),
('Mateo', 'Jiménez'),
('Lucía', 'Cruz'),
('Sebastián', 'Reyes'),
('Victoria', 'Rojas'),
('Nicolás', 'Mendoza'),
('Emilia', 'Castillo'),
('Samuel', 'Salazar'),
('Renata', 'Ponce'),
('Gabriel', 'Cordero'),
('Mariana', 'Aguilar'),
('Alejandro', 'Ceballos'),
('Juliana', 'Bermúdez'),
('Pablo', 'Cárdenas'),
('Daniela', 'Serrano'),
('Cristian', 'Cruz'),
('Natalia', 'Patiño'),
('Julián', 'Salas'),
('Mía', 'Quintero'),
('Esteban', 'Gómez'),
('Valeria', 'Castaño'),
('Rafael', 'Hidalgo'),
('Santiago', 'Márquez'),
('Luciana', 'Pérez'),
('Felipe', 'Alvarez'),
('Ariana', 'Córdoba'),
('Martín', 'Soto'),
('Diana', 'López'),
('Gonzalo', 'Rincón'),
('Claudia', 'Salinas'),
('Hugo', 'Cifuentes'),
('Cecilia', 'Mora'),
('Ricardo', 'Pizarro'),
('Tatiana', 'Bolaños'),
('Leonardo', 'Cruz'),
('Margarita', 'Salazar'),
('Oscar', 'García');

-- CATEGORÍAS
INSERT INTO categorias_categoria (nombre) VALUES
('Ficción'),
('No Ficción'),
('Ciencia'),
('Historia'),
('Biografía'),
('Fantasía'),
('Misterio'),
('Romance'),
('Ciencia Ficción'),
('Terror'),
('Autoayuda'),
('Desarrollo Personal'),
('Literatura Infantil'),
('Cocina'),
('Viajes');

-- EDITORIALES
INSERT INTO editoriales_editorial (nombre) VALUES
('Editorial Planeta'),
('Penguin Random House'),
('Grupo Anaya'),
('Ediciones SM'),
('HarperCollins'),
('Alfaguara'),
('Tusquets Editores'),
('Roca Editorial'),
('Ediciones B'),
('Lumen'),
('Anagrama'),
('Ediciones Akal'),
('Círculo de Lectores'),
('Editorial Espasa'),
('Ediciones Salamandra'),
('Ediciones Urano'),
('Editorial Océano'),
('Ediciones Destino'),
('Editorial Siruela'),
('Editorial La Galera'),
('Ediciones El País'),
('Editorial Juventud'),
('Ediciones del Serbal'),
('Editorial Planeta de Agostini'),
('Editorial Ediciones de la Torre');
